export const GET_ITEMS = 'GET_ITEMS'
export const GET_ITEMS_STARTED = 'GET_ITEMS_STARTED'
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS'
export const GET_ITEMS_FAILED = 'GET_ITEMS_FAILED'

export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
export const SET_SCENE = 'SET_SCENE'
export const SET_PAGE = 'SET_PAGE'

export const SEARCH_STARTED = 'SEARCH_STARTED'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const MORE_SEARCH_SUCCESS = 'MORE_SEARCH_SUCCESS'
export const SEARCH_FAILED = 'SEARCH_FAILED'

export const VIDEO_FETCH_STARTED = 'VIDEO_FETCH_STARTED'
export const VIDEO_FETCH_SUCCESS = 'VIDEO_FETCH_SUCCESS'
export const VIDEO_FETCH_FAILED = 'VIDEO_FETCH_FAILED'
export const VIDEO_FETCH_UNLOAD = 'VIDEO_FETCH_UNLOAD'

export const ADD_TO_PLAYLIST = 'ADD_TO_PLAYLIST'
export const SELECT_PLAYLIST_ITEM = 'SELECT_PLAYLIST_ITEM'
