export const SET_PAGE = 'SET_PAGE'

export const ADD_ITEM_TO_INVOICE = 'ADD_ITEM_TO_INVOICE'

export const FETCH_BEERS_START = 'FETCH_BEERS_START'
export const FETCH_BEERS_SUCCESS = 'FETCH_BEERS_SUCCESS'
export const FETCH_BEERS_FAILURE = 'FETCH_BEERS_FAILURE'

export const PASS = 'PASS'
export const SET_PRODUCT = 'SET_PRODUCT'
