export const SET_LOADING = 'SET_LOADING'
export const SET_PAGE = 'SET_PAGE'
export const SET_PRODUCT = 'SET_PRODUCT'

export const ADD_ITEM_TO_INVOICE = 'ADD_ITEM_TO_INVOICE'

export const FETCH_BEERS_START = 'FETCH_BEERS_START'
export const FETCH_BEERS_SUCCESS = 'FETCH_BEERS_SUCCESS'
export const FETCH_BEERS_FAILURE = 'FETCH_BEERS_FAILURE'

export const CREATE_TOKEN_START = 'CREATE_TOKEN_START'
export const CREATE_TOKEN_SUCCESS = 'CREATE_TOKEN_SUCCESS'
export const CREATE_TOKEN_FAILURE = 'CREATE_TOKEN_FAILURE'

export const PASS = 'PASS'
